### ISSUE TITLE
Empty input will result in a crash

### ISSUE THREAD

**Issue by Deukhoofd** [terrajobst/minsk#26]
Leaving a blank input or just whitespace results in a crash

```
»     

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Minsk.CodeAnalysis.Binding.BoundScope.TryLookup(String name, VariableSymbol& variable) in /home/nathan/Projects/minsk/src/Minsk/CodeAnalysis/Binding/BoundScope.cs:line 28
   at Minsk.CodeAnalysis.Binding.Binder.BindNameExpression(NameExpressionSyntax syntax) in /home/nathan/Projects/minsk/src/Minsk/CodeAnalysis/Binding/Binder.cs:line 146
   at Minsk.CodeAnalysis.Binding.Binder.BindExpression(ExpressionSyntax syntax) in /home/nathan/Projects/minsk/src/Minsk/CodeAnalysis/Binding/Binder.cs:line 119
   at Minsk.CodeAnalysis.Binding.Binder.BindExpressionStatement(ExpressionStatementSyntax syntax) in /home/nathan/Projects/minsk/src/Minsk/CodeAnalysis/Binding/Binder.cs:line 106
   at Minsk.CodeAnalysis.Binding.Binder.BindStatement(StatementSyntax syntax) in /home/nathan/Projects/minsk/src/Minsk/CodeAnalysis/Binding/Binder.cs:line 69
   at Minsk.CodeAnalysis.Binding.Binder.BindGlobalScope(BoundGlobalScope previous, CompilationUnitSyntax syntax) in /home/nathan/Projects/minsk/src/Minsk/CodeAnalysis/Binding/Binder.cs:line 24
   at Minsk.CodeAnalysis.Compilation.get_GlobalScope() in /home/nathan/Projects/minsk/src/Minsk/CodeAnalysis/Compilation.cs:line 35
   at Minsk.CodeAnalysis.Compilation.Evaluate(Dictionary`2 variables) in /home/nathan/Projects/minsk/src/Minsk/CodeAnalysis/Compilation.cs:line 50
   at Minsk.Program.Main() in /home/nathan/Projects/minsk/src/mc/Program.cs:line 67
```

**Comment by Deukhoofd** [comment]
Fixed in Episode 7
